---
# Apache configuration tasks for Debian systems.

- name: Service enabled.
  service:
    name: "{{ apache_service }}"
    enabled: yes

- name: Configure service port.
  lineinfile:
    path: "{{ apache_config_dir }}/ports.conf"
    regex: "{{ item.regex }}"
    line: "{{ item.line }}"
    state: present
    mode: 0644
  with_items: "{{ apache_port_configuration }}"
  notify: restart apache

- name: Enable additional modules.
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_enable_modules }}"
  when: apache_enable_modules is defined
  notify: restart apache

- name: Disable modules.
  apache2_module:
    name: "{{ item }}"
    state: absent
  with_items: "{{ apache_disable_modules }}"
  when: apache_disable_modules is defined
  notify: restart apache

...