---
# Provisioning tasks for Debian systems.

- name: Repositories update.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Check packets state.
  apt:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_status }}"
...