---
# This file charge diferents variables and tasks based on host operating system and Apache version.
# This allows us to use this role to manage the apache instalation and configuration independently of 
# the operating system, distribution (Debian, CentOS, etc) owned by the hosts or Apache version 
# installed.

- name: Include OS variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define server packages.
  set_fact:
    apache_packages: "{{ __apache_packages }}"
  when: apache_packages is not defined

- name: Include web server installation tasks.
  include: "{{ ansible_os_family }}-apache.yml"

- name: Get Apache version.
  command: "{{ apache_daemon_path }}{{ apache_service }} -v"
  changed_when: false
  register: _apache_version

- name: Define Apache version installed.
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"

- name: Include Apache version variables.
  include_vars: apache-24.yml
  when: "apache_version.split('.')[1] == '4'"

- name: Include server configuration tasks.
  include: "{{ ansible_os_family }}-config.yml"
...