---
# Provisioning tasks for Debian systems.

- name: Update cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages.
  apt:
    name: "{{ commons_packages }}"
    state: "{{ commons_packages_status }}"

...
