---
- name: Cargando variables de distribución
  include_vars: "{{ ansible_os_family }}.yml"

- name: Definiendo paquetes a instalar
  set_fact:
    commons_packets: "{{ __commons_packets }}"
  when: commons_packets is not defined

- name: Instalación de paquetes
  include_tasks: "{{ ansible_os_family }}-commons.yml"

- name: Configurando del sistema
  include_tasks: "{{ ansible_os_family }}-configure.yml"
...
