- name: Update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Permit Ansible check mode
  apt:
    name: python-apt
    state: latest

- name: Configure timezones
  timezone:
    name: Europe/Madrid