---
# This file define DEFAULT variables for Apache web server configuration. 
# - It's important that variables defined here are OS/Apache-version independent.
# - Specific OS variables (like necesaries packages to install Apache or daemon name) 
#   are defined in 'apache/vars/(os_family).yml'
# - Specific Apache version variables are defined in 'apache/vars/apache-version.yml'

# Apache packages state; present (installed) or absent (uninstalled)
apache_packages_status: present

# Apache server port
apache_port: 80

# Enabled additional modules
apache_enable_modules: 
    - rewrite
    - expires
    - headers

# Disabled modules
#apache_disable_modules:
#    - rewrite

# Apache service restart state (restarted/reloaded)
apache_restart_status: restarted
...